___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [8]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [8]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [14]:
np.random.rand(1)

array([0.87884694])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [15]:
np.random.randn(25).reshape(5,5)

array([[ 0.97615499, -0.1001167 , -0.89927033,  0.53912694,  0.31235377],
       [ 1.53617747, -0.00230896,  0.97584907, -0.85473558, -0.66915904],
       [ 0.39523577, -1.41741285,  2.21789418,  0.34756476, -1.36808701],
       [-0.04912531,  2.01335563,  0.54691954,  0.62588046, -1.36971641],
       [ 0.67291976, -0.00432318, -0.32539165, -1.01953867,  1.0386604 ]])

#### Create the following matrix:

In [28]:
np.linspace(0,1,100).reshape(10,10).shape

(10, 10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [2]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [10]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
np.array([np.arange(12,16),np.arange(17,21),np.arange(22,26)])
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [12]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3,-1]

20

20

In [15]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[:3,1].reshape(3,1)
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [16]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[-1,]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[[-2,-1],]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [20]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [21]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [30]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Great Job!

In [10]:
import pandas as pd


In [15]:
list('ABCDE')

['A', 'B', 'C', 'D', 'E']

In [16]:
df = pd.DataFrame(np.random.randn(5,4),list('ABCDE'),list('WXYZ'))

In [17]:
df

W         X         Y         Z
A -0.568432  1.818408 -0.128965 -0.087867
B  0.710231  0.130724  0.281374  0.478143
C -0.165122  0.593354 -0.679540  1.649948
D  0.097091  0.566803  0.508722 -0.554256
E  0.789935 -0.552144 -0.184651 -1.345828

In [19]:
df[df['X']>0][['X','Y']]

X         Y
A  1.818408 -0.128965
B  0.130724  0.281374
C  0.593354 -0.679540
D  0.566803  0.508722

In [21]:
df.loc['D']

W    0.097091
X    0.566803
Y    0.508722
Z   -0.554256
Name: D, dtype: float64

In [26]:
df.loc['D',['X','Y']]

X    0.566803
Y    0.508722
Name: D, dtype: float64

In [34]:
df.iloc[1,1:3]

X    0.130724
Y    0.281374
Name: B, dtype: float64

In [36]:
df[(df['X'] > 0) & (df['Y'] > 0)]

W         X         Y         Z
B  0.710231  0.130724  0.281374  0.478143
D  0.097091  0.566803  0.508722 -0.554256